/*********** ---------------------------------------------|
 \\\//////  http://www.zhangyongfeng.com/                |
 | @   @ |  ---------------------------------------------|
 |   L   |  Zhang Yongfeng <artwc@outlook.com>           |
 (   v   )  Created by 2019/1/3                          |
 \_____/   _____________________________________________|
 * @license GPL
 * @version 1.0.0
 * @fileOverview for .html 16:41
 */
function loadJs(n,t){k("<script>").add({id:n,src:t,async:"async",defer:"defer"}).appendTo(document.head)}"17k.com"===k.domain?loadJs("qd2885765656071f1cae92a68e65323bd2d9e8bef032","https://wp.qiye.qq.com/qidian/2885765656/071f1cae92a68e65323bd2d9e8bef032"):(k.apiPublicParam.appKey=3156022953,k((function(){window.AuthorH5&&(window.AuthorH5.id="Author_4yt_PC"),loadJs("qd2885765656dce0f1482dd0fb0fa6ec57fcb3e3f78c","https://wp.qiye.qq.com/qidian/2885765656/dce0f1482dd0fb0fa6ec57fcb3e3f78c")})),k.loadCss("//static."+k.domain+"/author/skin/sites/"+k.domain+".css",(function(){window.menu_author_fuli.href="//www.4yt.net/static/html/fuli/2020/"}))),k.login((function(n){if(k.api("/ck/author/mine").get().send((function(){}),(function(n){1204===n.code?-1===location.href.indexOf("/manage/startAuthor.html")&&location.replace("/manage/startAuthor.html"):k.alert({text:n.msg,type:"failed",confirmText:"刷新重试",confirm:function(){location.reload()},cancelText:"返回首页",cancel:function(){location.href="//www."+k.domain+"/"}})})),window.menu_newBookGift){var t="_authorIsShowGiftMenu"+n.id;"1"===k.cookie(t)?window.menu_newBookGift.style.display="block":(k.api("/ck/author/book").get({num:0}).send((function(n,o){o.totalNum<1&&!n.wordCount&&(window.menu_newBookGift.style.display="block",k.cookie(t,1,6912e5))})),k.api("/ck/task/new-book").get().send((function(n){n.bookInfo?(window.menu_newBookGift.style.display="block",k.cookie(t,1,6912e5)):k.cookie(t,0,6912e5)}),(function(){})))}k.api("/ck/author/labo/is/contract").get().send((function(n){n&&!0===n[0]&&window.labo_menu&&(window.labo_menu.style.display="block")}))})),k((function(){k(".leftMenu a").forEach((function(n){if(-1!==n.href.indexOf(location.pathname.replace(/^(\/\w*).*/,"$1")))return n.parentNode.className="now",!0}))}));var getStatus=function(n){var t;return n.authLevel&&4===n.authLevel.id?(t=4,n.isVIP&&1===n.isVIP.id&&(t=5),3===n.status.id&&(t=2)):(t=3,1===n.status.id?t=7:2===n.status.id?t=6:3===n.status.id&&(t=2)),t};window.goCreateBook=function(){window.location.href="4yt.net"===k.domain?"/manage/newBook.html?site=syt":"/manage/create.html"};
