server:
  servlet:
    context-path: /aiyue
  port: 8088
  max-http-header-size: 102400


spring:
  datasource:  # 数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aiyue?userUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
    username: root
    password: admin

  thymeleaf:
    # encoding: UTF-8
    # prefix: classpath:/templates/
    # suffix: .html
    mode: HTML5  # 视图模型
    cache: false # 模板缓存

  resources:
    static-locations: classpath:/META- INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/
    # 静态资源路径
  servlet:
    #设置文件大小限制  默认为 1mb
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

