/*********** ---------------------------------------------|
 \\\//////  http://www.zhangyongfeng.com/                |
 | @   @ |  ---------------------------------------------|
 |   L   |  Zhang Yongfeng <artwc@outlook.com>           |
 (   v   )  Created by 2019/1/3                          |
 \_____/   _____________________________________________|
 * @license GPL
 * @version 1.0.0
 * @fileOverview for .html
 */
function loadJs(o,e){k("<script>").add({id:o,src:e,async:"async",defer:"defer"}).appendTo(document.head)}"17k.com"===k.domain?loadJs("qd2885765656071f1cae92a68e65323bd2d9e8bef032","https://wp.qiye.qq.com/qidian/2885765656/071f1cae92a68e65323bd2d9e8bef032"):(k.apiPublicParam.appKey=3156022953,k(function(){window.AuthorH5&&(window.AuthorH5.id="Author_4yt_PC"),loadJs("qd2885765656dce0f1482dd0fb0fa6ec57fcb3e3f78c","https://wp.qiye.qq.com/qidian/2885765656/dce0f1482dd0fb0fa6ec57fcb3e3f78c")}),k.loadCss("//static."+k.domain+"/author/skin/sites/"+k.domain+".css")),k.login(function(o){if(k.api("/ck/author/mine").get().send(function(){},function(o){1204===o.code?location.href.indexOf("/manage/startAuthor.html")===-1&&location.replace("/manage/startAuthor.html"):k.alert({text:o.msg,type:"failed",confirmText:"刷新重试",confirm:function(){location.reload()},cancelText:"返回首页",cancel:function(){location.href="//www."+k.domain+"/"}})}),window.menu_newBookGift){var e="_authorIsShowGiftMenu"+o.id;"1"===k.cookie(e)?window.menu_newBookGift.style.display="block":(k.api("/ck/author/book").get({num:0}).send(function(o,n){n.totalNum<1&&!o.wordCount&&(window.menu_newBookGift.style.display="block",k.cookie(e,1,6912e5))}),k.api("/ck/task/new-book").get().send(function(o){o.bookInfo?(window.menu_newBookGift.style.display="block",k.cookie(e,1,6912e5)):k.cookie(e,0,6912e5)},function(){}))}k.api("/ck/author/labo/is/contract").get().send(function(o){o&&o[0]===!0&&window.labo_menu&&(window.labo_menu.style.display="block")})}),k(function(){k(".leftMenu a").forEach(function(o){if(o.href.indexOf(location.pathname.replace(/^(\/\w*).*/,"$1"))!==-1)return o.parentNode.className="now",!0})});var getStatus=function(o){var e;return o.authLevel&&4===o.authLevel.id?(e=4,o.isVIP&&1===o.isVIP.id&&(e=5),3===o.status.id&&(e=2)):(e=3,1===o.status.id?e=7:2===o.status.id?e=6:3===o.status.id&&(e=2)),e};window.goCreateBook=function(){window.location.href="4yt.net"===k.domain?"/manage/newBook.html?site=syt":"/manage/create.html"};